  deploy-to-vm:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy on Azure VM
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} <<EOF

          echo "🔐 Logging into ACR..."
          echo "${{ secrets.ACR_PASSWORD }}" | docker login testingacrhello.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

          echo "📥 Pulling image testingacrhello.azurecr.io/myapp:${IMAGE_TAG}"
          docker pull testingacrhello.azurecr.io/myapp:${IMAGE_TAG}

          echo "🛑 Removing old container"
          docker rm -f myapp || true

          echo "🚀 Starting new container"
          docker run -d --name myapp --restart unless-stopped -p 9000:9000 testingacrhello.azurecr.io/myapp:${IMAGE_TAG}

          echo "✅ Deployment finished!"
EOF
